[theme]
primaryColor="#76309B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#f7f0fa"
textColor="#000000"

[server]
maxUploadSize=2048
enableXsrfProtection=true
enableCORS=false

[browser]
gatherUsageStats=false 