[theme]
primaryColor="#7630FF"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"

[server]
maxUploadSize=50
enableXsrfProtection=true
enableCORS=false

[browser]
gatherUsageStats=false 